project:
  type: website
  output-dir: docs
website:
  title: "sfansler.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Example_analysis.qmd
        text: Example Analysis
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



