---
title: "About"
---

## Education
MS in Biostatistics, University of Michigan, 2021

BA in Statistics and Music, Butler University, 2017

## Biography
I attended my undergraduate at Butler University with a double major in Statistics and Music. While at Butler, I combined my passions for music and statistics by completing a research project in the Indianapolis community. For this project, I worked with the Psychology department to implement a music intervention for dementia patients at a local nursing home. The goal of the project was to see if listening to a personalized playlist of music for one hour would improve older adults' dementia-caused sundowning symptoms, both short-term (same day) and long term (across 3 months). This experience instilled a passion for research in public health, especially among the older adult population.

After graduating from Butler, to further pursue my newfound passion, I pursued my Master's degree in Biostatistics from the University of Michigan. During my Master's, I continued my research by collaborating with the Epidemiology department to implement machine learning techniques to predict cardiovascular disease mortality using environmental metal mixtures. At Michigan, I learned the technical skills required to be a practicing Biostatistician and developed a solid theoretical foundation to continue my education.

I am currently pursuing my Ph.D. in the Biostatistics department at the Johns Hopkins School of Public Health. At Hopkins, I hope to develop and improve methodology for measuring biomarkers and physical activity using wearable devices and imaging technology, especially for older adults.

After completing my education, I hope to lead research in the field of wearable devices and mobile health, developing new rigorous statistical methodology and paving the way for application of cutting-edge technology to improve public health outcomes for older adults as well as the general population.
